### ISSUE TITLE
cannot use your pretrained model

### ISSUE THREAD

**Issue by CHENGY12** [Yugnaynehc/banet#2]
Hello, I tried to to use your pretrained model, but it mismatch the model since I don't have the vocabulary dictionary (thus there is something wrong with the vocab size as well as the word matching).  So could you please help me to test your pretrained model?

**Comment by Yugnaynehc** [comment]
I apologize for the late response. This repository had updated many times after the pretrained model  was trained, so the pretrained model is too old to use.
