### ISSUE TITLE
Error in evaluation.  How to fix it?

### ISSUE THREAD

**Issue by YuanEZhou** [Yugnaynehc/banet#4]
File "/disk/zye/banet-master/evaluate.py", line 64, in evaluate
    metrics = measure(prediction_txt_path, reference)
  File "/disk/zye/banet-master/evaluate.py", line 30, in measure
    cocoRes = reference.loadRes(crf.res)
  File "./coco-caption/pycocotools/coco.py", line 275, in loadRes
    anns    = json.load(open(resFile))
TypeError: coercing to Unicode: need string or buffer, list found

Process finished with exit code 1

How to fix it?  @Yugnaynehc   
Thanks!

**Comment by Yugnaynehc** [comment]
Hi, sorry for the delayed response. It looks like the *coco-caption* issue, and I suggest the resFile is not correctly generated or opened. Could you please print the return value of open(resFile) before line 275 of coco.py, and figure it out what is the problem there.

**Comment by Yugnaynehc** [comment]
Cheers! 🍻

**Comment by AcodeC** [comment]
I got the same error, How to fix it? Could someone tell me?
